import { Header } from "@/components/Header";
import { SEO } from "@/components/SEO";
import { SiteFooter } from "@/components/SiteFooter";

const DataSources = () => (
  <div className="min-h-screen bg-background">
    <SEO
      title="Data Sources & Attribution — IntegralStocks"
      description="Where IntegralStocks gets its stock prices, market news, and AI insights."
      path="/data-sources"
    />
    <Header />
    <main className="container mx-auto px-4 py-10 max-w-3xl prose prose-neutral dark:prose-invert">
      <h1>Data sources & attribution</h1>
      <ul>
        <li><strong>Quotes, charts, and search:</strong> Yahoo Finance public endpoints. Quotes may be delayed.</li>
        <li><strong>Market news:</strong> Yahoo Finance news feeds and publisher RSS.</li>
        <li><strong>AI insights:</strong> Generated by large language models via the Lovable AI Gateway (Google Gemini and OpenAI GPT families).</li>
        <li><strong>Logos and trademarks:</strong> Property of their respective owners and used for identification only.</li>
      </ul>
      <p>
        We are not affiliated with Yahoo, Google, or OpenAI. If you are a data provider and have a
        concern, please <a href="/contact">contact us</a>.
      </p>
    </main>
    <SiteFooter />
  </div>
);

export default DataSources;
