import { Header } from "@/components/Header";
import { SEO } from "@/components/SEO";
import { SiteFooter } from "@/components/SiteFooter";

const FAQS = [
  {
    q: "What is IntegralStocks?",
    a: "IntegralStocks is a free, beginner-friendly stock market dashboard designed to help new investors understand how the market works. You can track live stock prices, read market news, and view plain‑English AI insights that explain major price movements and trends.",
  },
  {
    q: "Is IntegralStocks free?",
    a: "Yes. All core features — including stock quotes, charts, news summaries, and the paper trading simulator — are completely free to use.",
  },
  {
    q: "Where do the stock prices come from?",
    a: "Stock quotes and charts are sourced from publicly accessible Yahoo Finance endpoints. Some exchanges may provide delayed data, typically by up to 15 minutes.",
  },
  {
    q: "How accurate are the AI insights?",
    a: "AI insights are generated by large language models and summarize publicly available news and market information. They are educational explanations, not financial advice, and may occasionally contain inaccuracies. Always verify important information with primary sources.",
  },
  {
    q: "Can I trade real stocks on IntegralStocks?",
    a: "No. IntegralStocks offers a paper trading simulator that uses simulated money so you can practice strategies risk‑free. We do not support real trading or connect to brokerage accounts.",
  },
  {
    q: "Do I need an account?",
    a: "You can browse stock prices, charts, and news without an account. Creating an account allows you to save a watchlist and use the paper trading simulator.",
  },
  {
    q: "Is IntegralStocks safe to use?",
    a: "Yes. The site uses modern authentication, encrypted HTTPS connections, and never asks for brokerage credentials, payment information, or sensitive financial data.",
  },
];

const FAQ = () => (
  <div className="min-h-screen bg-background">
    <SEO
      title="FAQ — IntegralStocks (Beginner Stock Market Questions)"
      description="Answers to common questions about IntegralStocks: how it works, where data comes from, AI insights, and the free trading simulator."
      path="/faq"
      jsonLd={{
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: FAQS.map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      }}
    />
    <Header />
    <main className="container mx-auto px-4 py-10 max-w-3xl">
      <h1 className="text-3xl font-bold mb-6">Frequently Asked Questions</h1>
      <div className="space-y-6">
        {FAQS.map((f) => (
          <section key={f.q}>
            <h2 className="text-lg font-semibold mb-1">{f.q}</h2>
            <p className="text-muted-foreground leading-relaxed">{f.a}</p>
          </section>
        ))}
      </div>
    </main>
    <SiteFooter />
  </div>
);

export default FAQ;
