import { Header } from "@/components/Header";
import { SEO } from "@/components/SEO";
import { SiteFooter } from "@/components/SiteFooter";

const FAQS = [
  {
    q: "What is IntegralStocks?",
    a: "IntegralStocks is a free, beginner-friendly stock market dashboard. You can track live stock prices, read market news, and get plain-English AI insights that explain why a stock moved.",
  },
  {
    q: "Is IntegralStocks free?",
    a: "Yes. The dashboard, news, charts, and paper trading simulator are completely free to use.",
  },
  {
    q: "Where do the stock prices come from?",
    a: "Stock quotes and charts come from Yahoo Finance public endpoints. Prices may be delayed by up to 15 minutes for some exchanges.",
  },
  {
    q: "How accurate are the AI insights?",
    a: "AI insights are generated by large language models and summarize public news. They are educational, not financial advice, and can occasionally be wrong. Always verify with primary sources before acting.",
  },
  {
    q: "Can I trade real stocks on IntegralStocks?",
    a: "No. IntegralStocks includes a paper trading simulator using simulated money so you can practice strategies risk-free. We do not execute real trades.",
  },
  {
    q: "Do I need an account?",
    a: "You can browse stock prices and news without an account. An account lets you save a watchlist and use the trading simulator.",
  },
  {
    q: "Is IntegralStocks safe to use?",
    a: "Yes. We use modern authentication, encrypted connections (HTTPS), and never ask for brokerage credentials or money.",
  },
];

const FAQ = () => (
  <div className="min-h-screen bg-background">
    <SEO
      title="FAQ — IntegralStocks (Beginner Stock Market Questions)"
      description="Answers to the most common questions about IntegralStocks: what it is, how AI insights work, data sources, and the free trading simulator."
      path="/faq"
      jsonLd={{
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: FAQS.map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      }}
    />
    <Header />
    <main className="container mx-auto px-4 py-10 max-w-3xl">
      <h1 className="text-3xl font-bold mb-6">Frequently asked questions</h1>
      <div className="space-y-6">
        {FAQS.map((f) => (
          <section key={f.q}>
            <h2 className="text-lg font-semibold mb-1">{f.q}</h2>
            <p className="text-muted-foreground leading-relaxed">{f.a}</p>
          </section>
        ))}
      </div>
    </main>
    <SiteFooter />
  </div>
);

export default FAQ;
